services:
    reverseproxy:
        build: nginx-cache
        ports:
            - 80:80
        restart: always

    java:
        depends_on:
            - reverseproxy
        ports:
            - 8080:8080
        build: java-app
        restart: always
